# Generated by Django 4.2.1 on 2023-05-29 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectedShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_punch_in', models.DateTimeField()),
                ('corrected_punch_out', models.DateTimeField()),
                ('corrected_break_start', models.DateTimeField(blank=True, null=True)),
                ('corrected_break_end', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_in', models.DateTimeField()),
                ('punch_out', models.DateTimeField()),
                ('break_start', models.DateTimeField(blank=True, null=True)),
                ('break_end', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='timepunchcorrection',
            name='time_punch',
        ),
        migrations.RemoveField(
            model_name='timepunchcorrection',
            name='user',
        ),
        migrations.DeleteModel(
            name='TimePunch',
        ),
        migrations.DeleteModel(
            name='TimePunchCorrection',
        ),
        migrations.AddField(
            model_name='correctedshift',
            name='original_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clock.shift'),
        ),
        migrations.AddField(
            model_name='correctedshift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
