# Generated by Django 4.2.1 on 2023-05-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0002_correctedshift_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='punch_out',
            field=models.DateTimeField(null=True),
        ),
    ]
